{
 "title": "jwt-pizza-dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(active_users_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cpu percentage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Authentication attempts per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    { "expr": "rate(auth_success_total[1m])", "legendFormat": "__auto" },
    {
     "expr": "rate(auth_failure_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "total_latency_avg_milliseconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory usage percentage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizza creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "pizza_latency_avg_milliseconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(requests_total[1m]))",
     "legendFormat": "__auto"
    },
    { "expr": "sum(rate(requests_total[1m]))", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Revenue/min",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizza_revenue_USD_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful and failed purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "sum(pizza_failure_total)", "legendFormat": "__auto" },
    { "expr": "rate(pizza_success_total[1m])", "legendFormat": "__auto" }
   ]
  }
 ]
}